name: RealLifeYogi
favicon: null
layout_spectrum: 0.94214
typography_spectrum: 0.61821
title: 'Creating Resilient and Compassionate People & World'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9e3e9'
    - '#17110d'
    - '#574d30'
    - '#a47956'
    - '#2d7ec4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.40802005492150784
purpose: []
